In [6]:
#1. Create a vector, scalar, matrix and tensor with values of your choice using tf.constant()

In [2]:
import tensorflow as tf

In [4]:
#Scalar
scalar = tf.constant(7)
print(scalar)

tf.Tensor(7, shape=(), dtype=int32)


In [5]:
#Vector
vector = tf.constant([5, 2, 6])
print(vector)

tf.Tensor([5 2 6], shape=(3,), dtype=int32)


In [10]:
#Matrix
matrix = tf.constant([[1, 2, 3] , [2, 5, 6]])
print(matrix)

tf.Tensor(
[[1 2 3]
 [2 5 6]], shape=(2, 3), dtype=int32)


In [11]:
#Tensor
tensor = tf.constant([
    [[1, 2] , [3, 4]],
    [[5, 6],  [7, 8]]
])
print(tensor)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
