In [1]:
#Find the shape, rank and size of the tensors (which you created for Q1).

In [2]:
import tensorflow as tf

In [6]:
scalar = tf.constant(7)
print(scalar, end="\n\n")

vector = tf.constant([5, 2, 6])
print(vector, end="\n\n")

matrix = tf.constant([[1, 2, 3] , [2, 5, 6]])
print(matrix, end="\n\n")

tensor = tf.constant([
    [[1, 2] , [3, 4]],
    [[5, 6],  [7, 8]]
])
print(tensor, end="\n\n")

tf.Tensor(7, shape=(), dtype=int32)

tf.Tensor([5 2 6], shape=(3,), dtype=int32)

tf.Tensor(
[[1 2 3]
 [2 5 6]], shape=(2, 3), dtype=int32)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)



In [7]:
def tensor_info(name, t):
  print(f"{name}: \n Shape: {t.shape}\n Rank: {t.ndim}\n Size: {tf.size(t).numpy()}\n")

In [8]:
tensor_info("Scalar", scalar)
tensor_info("Vector", vector)
tensor_info("Matrix", matrix)
tensor_info("Tensor", tensor)

Scalar: 
 Shape: ()
 Rank: 0
 Size: 1

Vector: 
 Shape: (3,)
 Rank: 1
 Size: 3

Matrix: 
 Shape: (2, 3)
 Rank: 2
 Size: 6

Tensor: 
 Shape: (2, 2, 2)
 Rank: 3
 Size: 8

