In [1]:
#Create a tensor with random values between 0 and 1 with shape [224, 224, 3]

In [2]:
import tensorflow as tf

In [3]:
tensor = tf.random.uniform(shape = [224, 224, 3], minval = 0, maxval = 1)

In [7]:
print(f"Tensor shape:, {tensor.shape}")
print(f"Tensor dtype:, {tensor.dtype}")
print(tensor)

Tensor shape:, (224, 224, 3)
Tensor dtype:, <dtype: 'float32'>
tf.Tensor(
[[[0.45100296 0.29932225 0.23654008]
  [0.51997745 0.45792198 0.9441303 ]
  [0.73822796 0.2974795  0.9605191 ]
  ...
  [0.70210266 0.29051518 0.74006665]
  [0.52624583 0.00106072 0.2472359 ]
  [0.5384909  0.05492914 0.50788486]]

 [[0.4023248  0.15751123 0.5897126 ]
  [0.7392045  0.8046788  0.0511502 ]
  [0.48927438 0.9195062  0.1104002 ]
  ...
  [0.53651834 0.5258231  0.9183526 ]
  [0.08581018 0.00193405 0.3859154 ]
  [0.05541813 0.03184593 0.61323917]]

 [[0.7182578  0.9858873  0.15033138]
  [0.13734293 0.07269096 0.08178926]
  [0.19468987 0.86559427 0.24392629]
  ...
  [0.9146373  0.3189566  0.9017384 ]
  [0.43286812 0.97535944 0.11100602]
  [0.47608495 0.6968117  0.71731687]]

 ...

 [[0.9288217  0.86172867 0.01185012]
  [0.3398167  0.6711265  0.41116416]
  [0.5294658  0.6176156  0.04789519]
  ...
  [0.65262437 0.37627935 0.87937546]
  [0.7252897  0.23192143 0.901142  ]
  [0.9582064  0.80773854 0.68371975]]

